unstable_features = true

tab_spaces = 8
max_width = 120
imports_granularity = "One"

# use_small_heuristics = "Max"
# match_block_trailing_comma = true
# reorder_imports = true
# use_field_init_shorthand = true
# use_try_shorthand = true
