[package]
name = "tgt"
version = "0.1.3"
edition = "2021"
description = "A simple TUI for Telegram"
license = "Apache-2.0"
documentation = "https://docs.rs/crate/tgt/0.1.3"
homepage = "https://github.com/FedericoBruzzone/tgt"
repository = "https://github.com/FedericoBruzzone/tgt"
readme = "README.md"
keywords = ["tgt", "tgtui", "telegram", "tui", "tdlib"]
authors = ["Federico Bruzzone <federico.bruzzone.i@gmail.com>", "Andrea Longoni"]
categories = []
default-run = "tgt"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# [toolchain]
# channel = "nightly-2020-07-10"
# components = [ "rustfmt", "rustc-dev" ]
# targets = [ "wasm32-unknown-unknown", "thumbv2-none-eabi" ]
# profile = "minimal"

[dependencies]
crossterm = {version = "0.27.0", features = ["event-stream"]}
futures = "0.3.30"
lazy_static = "1.4.0"
ratatui = "0.26.1"
signal-hook = "0.3.17"
tdlib = "0.10.0"
tokio = {version = "1.36.0", features = ["full"]}
tracing = "0.1.40"
tracing-error = "0.2.0"
tracing-subscriber = {version = "0.3.18", features = ["env-filter"]}

[profile.dev]
incremental = true

