[package]
name = "tgt"
version = "0.1.5"
edition = "2021"
description = "A simple TUI for Telegram"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/crate/tgt/0.1.5"
homepage = "https://github.com/FedericoBruzzone/tgt"
repository = "https://github.com/FedericoBruzzone/tgt"
readme = "README.md"
keywords = [
    "tgt",
    "tgtui",
    "telegram",
    "tui",
    "tdlib",
]
authors = [
    "Federico Bruzzone <federico.bruzzone.i@gmail.com>",
    "Andrea Longoni",
]
default-run = "tgt"
build = "build.rs"
categories = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# [toolchain]
# channel = "nightly-2020-07-10"
# components = [ "rustfmt", "rustc-dev" ]
# targets = [ "wasm32-unknown-unknown", "thumbv2-none-eabi" ]
# profile = "minimal"

[dependencies]
config = "0.14.0"
crossterm = { version = "0.27.0", features = ["event-stream"] }
dirs = "5.0.1"
futures = "0.3.30"
lazy_static = "1.4.0"
ratatui = "0.26.3"
serde = "1.0.202"
tdlib = "0.10.0"
tokio = { version = "1.37.0", features = ["full"] }
tracing = "0.1.40"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "chrono"] }
tracing-appender = "0.2"
arboard = { version = "3.4.0", features = ["wayland-data-control", "wl-clipboard-rs"] }
chrono = "0.4.38"
ratatui-image = "1.0.0"
image = "0.25.1"

[build-dependencies]
dirs = "5.0.1"

[profile.dev]

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
strip = "debuginfo"
