# The core_window key bindings are usable in any app component.
[core_window]
keymap = [
  # Quit the application, example of multiple keys
  # { keys = ["w", "w"], command = "quit", description = "Quit the application"},

  # Quit the application
  # Note that when the prompt is focused, the "q" key will be used to type the letter "q".
  { keys = ["q"], command = "try_quit", description = "Quit the application"},
  # Quit the application
  { keys = ["ctrl+c"], command = "quit", description = "Quit the application"},
  # Focus the chat list
  { keys = ["alt+1"], command = "focus_chat_list", description = "Focus the chat list"},
  # Focus the chat
  { keys = ["alt+2"], command = "focus_chat", description = "Focus the chat"},
  # Focus the prompt
  { keys = ["alt+3"], command = "focus_prompt", description = "Focus the prompt"},
  # Unfocus the current component
  { keys = ["esc"], command = "unfocus_component", description = "Unfocus the current component"},
  # Increase the chat list size
  { keys = ["shift+alt+right"], command = "increase_chat_list_size", description = "Increase the chat list size"},
  # Decrease the chat list size
  { keys = ["shift+alt+left"], command = "decrease_chat_list_size", description = "Decrease the chat list size"},
  # Increase the prompt size
  { keys = ["shift+alt+up"], command = "increase_prompt_size", description = "Increase the prompt size"},
  # Decrease the prompt size
  { keys = ["shift+alt+down"], command = "decrease_prompt_size", description = "Decrease the prompt size"},
]

# The chat_list key bindings are only usable in the chat list component.
# When the chat list is focused, the chat list key bindings will be active.
[chat_list]
keymap = [
  # Select the next chat
  { keys = ["down"], command = "chat_list_next", description = "Select the next chat"},
  # Select the previous chat
  { keys = ["up"], command = "chat_list_previous", description = "Select the previous chat"},
  # Unselect the current chat
  { keys = ["left"], command = "chat_list_unselect", description = "Unselect the current chat"},
]

# The chat key bindings are only usable in the chat component.
# When the chat is focused, the chat key bindings will be active.
[chat]
keymap = [
  # Select the next message
  { keys = ["down"], command = "message_list_next", description = "Select the next message"},
  # Select the previous message
  { keys = ["up"], command = "message_list_previous", description = "Select the previous message"},
  # Unselect the current message
  { keys = ["left"], command = "message_list_unselect", description = "Unselect the current message"},
]

# The prompt key bindings are only usable in the prompt component.
# When the prompt is focused, the prompt key bindings will be active.
[prompt]

