# Application identifier for Telegram API access, which can be obtained at https:my.telegram.org
api_id = "94575"
# Application identifier hash for Telegram API access, which can be obtained at https:my.telegram.org
api_hash = "a3406de8d171bb422bb6ddf3bbd800e2"
# The path to the directory for the persistent database; if empty, the current working directory will be used
# If is not overridden, the database will be in the `tgt` directory.
# In Linux and MacOS, the path is:
# $HOME/tgt/.data/tg
# In Windows, the path is:
# C:\Users\YourUsername\tgt\.data\tg
database_dir = ".data/tg"
# Pass true to keep information about downloaded and uploaded files between application restarts
use_file_database = true
# Pass true to keep cache of users, basic groups, supergroups, channels and secret chats between restarts. Implies use_file_database
use_chat_info_database = true
# Pass true to keep cache of chats and messages between restarts. Implies use_chat_info_database
use_message_database = true
# IETF language tag of the user's operating system language; must be non-empty
system_language_code = "en"
# Model of the device the application is being run on; must be non-empty
device_model = "Desktop"
# Pass true to ignore original file names for downloaded files. Otherwise, downloaded files are saved under names as close as possible to the original name
ignore_file_names = true
