theme_enable = true
background_color = "black"

[default]

[chat_list]

[chat]

[prompt]

[status_bar]
size_info = { fg = "light_blue", bg = "black", bold = false, underline = false, italic = false }

[title_bar]

