[palette]
black = "#000000"
white = "#ffffff"
background = "#000000"
primary = "#00548e"
primary_variant = "#0073b0"
primary_light = "#94dbf7"
secondary = "#ca3f04"
secondary_variant = "#e06819"
secondary_light = "#fcac77"
ternary = "#696969"
ternary_variant = "#808080"
ternary_light = "#6e7e85"
surface = "#141414"
on_surface = "#dcdcdc"
error = "#D50000"
on_error = "#FFCDD2"

[common]
border_component_focused = { fg = "secondary", bg = "background", bold = false, underline = false, italic = false }
item_selected = { fg = "", bg = "surface", bold = true, underline = false, italic = false }
timestamp = { fg = "ternary_light", bg = "background", bold = false, underline = false, italic = false }

[chat_list]
self = { fg = "primary", bg = "background", bold = false, underline = false, italic = false }
item_selected = { fg = "", bg = "primary", bold = false, underline = false, italic = false }
item_chat_name = { fg = "primary_light", bg = "background", bold = true, underline = false, italic = false }
item_message_content = { fg = "secondary_light", bg = "background", bold = false, underline = false, italic = true }
item_unread_counter = { fg = "secondary", bg = "background", bold = true, underline = false, italic = false }


[chat]
self = { fg = "primary", bg = "background", bold = false, underline = false, italic = false }
chat_name = { fg = "secondary", bg = "background", bold = true, underline = false, italic = false }
message_myself_name = { fg = "primary_light", bg = "background", bold = true, underline = false, italic = false }
message_other_name = { fg = "secondary_light", bg = "background", bold = true, underline = false, italic = false }
message_myself_content = { fg = "primary_variant", bg = "background", bold = false, underline = false, italic = false }
message_other_content = { fg = "secondary_variant", bg = "background", bold = false, underline = false, italic = false }

[prompt]
self = { fg = "primary", bg = "background", bold = false, underline = false, italic = false }
message_text = { fg = "primary_light", bg = "background", bold = false, underline = false, italic = false }
message_text_selected = { fg = "secondary_light", bg = "ternary", bold = false, underline = false, italic = true }
message_preview_text = { fg = "ternary", bg = "background", bold = false, underline = false, italic = false }

[status_bar]
self = { fg = "on_surface", bg = "surface", bold = false, underline = false, italic = false }
size_info_text = { fg = "primary_light", bg = "surface", bold = false, underline = false, italic = false }
size_info_numbers = { fg = "secondary_light", bg = "surface", bold = false, underline = false, italic = true }
press_key_text = { fg = "primary_light", bg = "surface", bold = false, underline = false, italic = false }
press_key_key = { fg = "secondary_light", bg = "surface", bold = false, underline = false, italic = true }
message_quit_text = { fg = "primary_light", bg = "surface", bold = false, underline = false, italic = false }
message_quit_key = { fg = "secondary_light", bg = "surface", bold = false, underline = false, italic = true }
open_chat_text = { fg = "primary_light", bg = "surface", bold = false, underline = false, italic = false }
open_chat_name = { fg = "secondary_light", bg = "surface", bold = false, underline = false, italic = true }

[title_bar]
self = { fg = "on_surface", bg = "surface", bold = false, underline = false, italic = false }
title1 = { fg = "primary_light", bg = "surface", bold = true, underline = true, italic = true }
title2 = { fg = "secondary_light", bg = "surface", bold = true, underline = true, italic = true }
title3 = { fg = "ternary_light", bg = "surface", bold = true, underline = true, italic = false }
